### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by john-at-whitesmiths** [djaodjin/djaodjin-saas#233]
Is there a timeline for having a compatible Django 3.0 version?

**Comment by smirolo** [comment]
Sorry I forgot to write an update on this issue. The last commit related to Django3.0 support is commit 11a3cf9f. Since then, the tests are run - and pass so far :) - with the following combinations:

- **Python:** 2.7, **Django:** 1.11, **Django Rest Framework:** 3.9.4
- **Python:** 3.6, **Django:** 2.2 ([LTS](https://www.djangoproject.com/download/)), **Django Rest Framework:** 3.11
- **Python:** 3.6, **Django:** 3.0 (latest), **Django Rest Framework:** 3.11
