### ISSUE TITLE
Coupon admin's filter feature usability problems

### ISSUE THREAD

**Issue by marmida** [djaodjin/djaodjin-saas#26]
The filter's auto-refresh on the coupon admin page fires off too eagerly. I made a short video of this behavior:
https://www.dropbox.com/sc/1hs0fpfp36agnuq/AAAlY-schXOxmYx0CLe5u9UQa

This has some negative effects:

1. it interrupts the user's typing, forcing them to type only one character per refresh
1. it loses focus, causing the user to re-focus on the text box after each refresh

In addition, it's confusing because:

1. the filter matches unexpected rows. I tried some number input that I figured should not match, and yet, it still found some rows with nothing obviously matched.
1. it's on the same line as the data-entry form for adding a new coupon. It's not immediately clear that one of these adds a row, while one filters the current results.
1. if no results are found, the display loses the input control for the filter expression, forcing the user to reload or hit back.

**Comment by smirolo** [comment]
Eager refresh and flow interruption
--
AngularJS might have a settings to slow down the eager API calls. The flow interruption, I never noticed. Is it a browser related issue or was I just blind?

The filter matches unexpected rows
--
In [saas/api/coupons.py](https://github.com/djaodjin/djaodjin-saas/blob/ef1f530af345755bf03022fc7210b46c33a7c283/saas/api/coupons.py), the following code picks up what is searched:

    class SmartCouponListMixin(SearchableListMixin, SortableListMixin):
    """
    Subscriber list which is also searchable and sortable.
    """
    search_fields = ['created_at',
                     'code',
                     'description',
                     'percent',
                     'ends_at',
                     'organization__full_name']

The non-obvious matches might come from the `JOIN` to retrieve `organization__full_name`. It turns out customers really love this feature. It might though be good to have some documentation on the page (coupon_list.html template) of what is the expected behavior of filter is and make sure it matches :).

The filter is on the same line as the data-entry form for adding a new coupon. It's not immediately clear that one of these adds a row, while one filters the current results.
--
That seemed like a good idea to pack `Add Coupon` and `Filter` tight on the screen ... but maybe not. If there are UI best practices for these sort of things, I am a taker.

If no results are found, the display loses the input control for the filter expression, forcing the user to reload or hit back.
--
Obviously a bug.

**Comment by marmida** [comment]
Regarding the above:

1. Matching on organization's name - the filter I used was a number that didn't occur in the coupon code, price, or pecent. It was a single digit. Perhaps this is because dates are being checked as strings, and they have lots of significant digits?
1. Filtering and adding - I looked around for a few articles, but I don't see anything I'd consider the "last word" of expert advice on the topic. These two were helpful: 
  http://designingwebinterfaces.com/ultimate-guide-to-table-ui-patterns
  http://www.jankoatwarpspeed.com/ultimate-guide-to-table-ui-patterns
  In general, I noted that there are no examples combining "in-table filtering" - having filtering controls inside the table rows - with "in-table adding" - having a form to add a new row also inside the table.

**Comment by marmida** [comment]
Further investigation into the first problem shows that it is indeed because of the backend search implementation of the filter API. Filtering is performed by the server-side in calls like `/cowork/api/coupons?o=code&ot=asc&q=8` for a query string of `8`. This ends up including the coupon "ARBORDAY" because the creation date includes at least one digit 8 in its microsecond-accurate timestamp. Here's a sample session:

```
>>> saas.models.Coupon.objects.using('cowork').filter(created_at__icontains='8')
[<Coupon: cowork-ARBORDAY>]
>>> saas.models.Coupon.objects.using('cowork').filter(created_at__icontains='8')[0].created_at
datetime.datetime(2015, 4, 9, 23, 59, 5, 818059, tzinfo=<UTC>)
```

The `django-extra-views` package is responsible for building the query; dropping into a debugger allows you to see how it builds a `Q` object expression: 

```
(Pdb) p search_pairs
[('created_at', u'icontains'), ('code', u'icontains'), ('description', u'icontains'), ('percent', u'icontains'), ('ends_at', u'icontains'), ('organization__full_name', u'icontains')]
```

See also: https://github.com/AndrewIngram/django-extra-views/blob/756fc71491dca74a887811ead4f937fbc1adde94/extra_views/contrib/mixins.py#L83

We should try to influence `django-extra-views` to only ever consider these columns with more relevant searches (e.g. on the same day, or gt/lt); or we should exclude these columns entirely.

**Comment by marmida** [comment]
This is working for me in #27. It could use code unification with the other CSV download I recently built, but I will make another pass to do that later.
