### ISSUE TITLE
Local, forward, remote, How to use stripe checkout?

### ISSUE THREAD

**Issue by j2l** [djaodjin/djaodjin-saas#305]
Hello again,
I tested the 3 modes and didn't see any change on the payment. Always getting:
![image](https://github.com/djaodjin/djaodjin-saas/assets/65325/719e01bb-fb57-4364-b637-030c523695f1)

I'd prefer to use stripe checkout.
Is there a way to do this?
Thanks!

**Comment by smirolo** [comment]
The 3 modes to configure the Stripe backend deal with where the [charges/payouts are created](https://djaodjin-saas.readthedocs.io/en/latest/backends.html#module-saas.backends.stripe_processor.base). If you are running a straightforward SaaS product, there is only one Stripe account. Just use the LOCAL mode then. If you are implementing a marketplace with multiple subscribers and providers there are two ways to [configure Stripe Connect](https://docs.stripe.com/connect) depending on the relationship of your customers with Stripe.

The Stripe backend is using the [Stripe PaymentIntent](https://docs.stripe.com/payments/paymentintents/lifecycle) APIs. If you want to use the Stripe-hosted checkout pages, maybe looking at the Flutterwave or RazorPay implementation could help (those two services do not allow self-hosted payment pages). I haven't looked at the workflow for Stripe-hosted Checkout pages, but the code to handle Stripe Webhooks is in [saas.backends.stripe_processor.views.py](https://github.com/djaodjin/djaodjin-saas/blob/master/saas/backends/stripe_processor/views.py) if that helps.

Otherwise if the issue is mostly out-of-the-box theme/templates, you might want to look at a more full-fledged project that uses djaodjin-saas like [djaoapp](https://github.com/djaodjin/djaoapp/).

**Comment by j2l** [comment]
Thank you very much for these details @smirolo 
I don't want to be PCI compliant to keep credit card numbers :smile, prefer to go the checkout way. Stripe Connect is expensive for now.

**Comment by smirolo** [comment]
@j2l Either way, using djaodjin-saas Stripe backend, or Stripe-hosted pages, you will be PCI compliant because what gets posted to your site is a token, neither the credit card information.

Note you may introduce a bug that posts the credit card number to your backend if you modify the input fields in [saas/templates/saas/_card_use.html](https://github.com/djaodjin/djaodjin-saas/blob/master/saas/templates/saas/_card_use.html#L27).
On the other hand, this method is legacy because by default [saas/static/js/djaodjin-stripe.js](https://github.com/djaodjin/djaodjin-saas/blob/01f58fce58815022e1ad50b449e9bdc5c852f26e/saas/static/js/djaodjin-stripe.js#L208) will mount [Stripe's Card Element](https://docs.stripe.com/payments/elements), bypassing the input fields in that template. The Javascript workflow in both cases is a bit different, but what the djaodjin-saas backend gets is a `stripeToken` that gets passed back to stripe from the backend to confirm payment.

**Comment by j2l** [comment]
OK, thank you for the precision. 
Since the client enters the credit card on the my server's page, it's still a no-go.
Personally, I already block third party scripts that are present when entering my CC details, because any update of third party script can embed a keylogger, so I won't propose a payment method that is on my small server, and even more offers a way to keep CC details (token) for convenience. Even Amazon stopped keeping CC details by default for convenience.
In this case, I only see Stripe Checkout, and a callback, as the solution.

**Comment by smirolo** [comment]
OK. Just for posterity, Stripe Web Components (loaded from Stripe servers) create an iframe on the page (so the CC details are entered on a page hosted by Stripe anyway). The only difference between Stripe Checkout and Stripe Web Components is the URL shown in the URL bar.

**Comment by j2l** [comment]
Ah, ok, I get your point. 
From a customer's point of view, it's totally different: You trust payment gateway (URL) because you use them often.

**Comment by smirolo** [comment]
Personnally, I don't trust a Website that hasn't spent the time to integrate payment processing properly and rely on processor-hosted pages. That feels like they couldn't be bothered. Is my data secure with that Website then?
On the other hand I also know many customers that are oblivious of where payment is processed. 
 I also know users that have no clue what/who Stripe is.

Guess it is more of a business than a technical decision to use Stripe Web components or Stripe-hosted checkout pages. You know your customers.
