### ISSUE TITLE
Date Ranges on funds and billing pages

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaodjin-saas#43]
It should be possible to download transactions based on date ranges.

**Comment by marmida** [comment]
Specifically, we'd like the "Funds" and "Billing" pages to have "start" and "end" dates. This acts as a filter, in addition to the search term filter already on the page. We'll also have to modify the CSV downloadable results, as well, in order to guarantee they match. Because of this, we should only attempt this after #41 is merged.
